spring:
  application:
    name: bulletin-board
  datasource:
    url: jdbc:h2:mem:demo;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=user
#    NON_KEYWORDS=userを入れないと、H2では予約語の為エラーとなる
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
      format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      encoding: UTF-8
      data-locations: classpath:data.sql
      # ? の中身（バインドパラメータ）を表示する
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace